service: aws-python-scheduled-cron
frameworkVersion: '>=1.2.0 <2.0.0'
provider:
  name: aws
  runtime: python2.7
functions:
  cron:
    handler: handler.run
    events:
      - schedule: rate(1 minute)
    runtime: python3.6
  secondCron:
    handler: handler.run
    events:
      - schedule: cron(0/2 * ? * MON-FRI *)